import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ThemeToggle from "@/components/ThemeToggle";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`{inter.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
        >
          <Header />
          <Sidebar containerStyles="hidden lg:flex fixed top-16 left-0 bottom-0 w-72 z-40 p-5 overflow-y-auto transition-all duration-300" />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html >
  );
}
